### ISSUE TITLE
Review Ticket for Presentations:

### ISSUE THREAD

**Issue by sonakshibhalla** [sonakshibhalla/tri2turtles#55]

**Comment by suneelanaidu** [comment]
Detailed wire frame
Nice home/theme pages
Good corelatin to CB concepts.

Implement Apis and more features learned in mini labs.

**Comment by connorw72** [comment]
Team Slimes - Nadira, Connor, Natalie, Paige

- The toggle of the images based on the information given is a great way to add detail.
- The Navbar change when going to a specific location is a great feature that makes the website look better.
-  The links to different information about where to stay and food is a great way to include information
- It is hard to read some of the information due to the colors, such as the white text wit h the purple background.

**Comment by NastyEthan** [comment]
Nasty - Ethan, Michael, James, Anirudh

- Detailed wireframe, looks like there is a lot of ideas that could be implemented
- The miscellaneous links like FAQs, ABOUT us, Navigation help are very informative (could look a bit more in place, rn looks uncomfortably placed)
- Links to the different websites are nice, buttons for easy access are nice
- The buttons that hover when accessing the navbar are visually impressive
- The changing images on the cite are interesting and help provide new information without scrolling
- Try to have each page aesthetically consistent, the backgrounds corresponding are good but each page looks too differently in terms of formatting and colors for the navbar and other aspects of the website. Fonts should be similar, buttons similar, similar proportions of the website, etc
